version: '2'

services:
  drone-server:
    image: drone/drone:latest
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://git.aswl.org
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/drone:latest
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8011/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
