# Git Server

gogs:
  image: "gogs/gogs:latest"
  container_name: "gogs"
  restart: always
  ports:
    - "8010:3000"
  volumes:
    - "./data/gogs:/data"
  links:
    - "postgresql"

postgresql:
  image: "kiasaki/alpine-postgres:latest"
  container_name: "gogs-psql"
  restart: always
  ports:
    - "8011:5432"
  volumes:
    - "./data/postgresql:/var/lib/postgresql"
  environment:
    - "POSTGRES_DB=gogs"
    - "POSTGRES_USER=gogs"
    - "POSTGRES_PASSWORD=gogs"
