# Git Server

gogs_data:
  image: 'busybox'
  tty: true
  container_name: 'git-store'
  volumes:
    - '/var/gogs/data:/data'
    - '/var/gogs/mysql:/var/lib/mysql'

gogs:
  image: "gogs/gogs:latest"
  container_name: "git"
  restart: 'always'
  ports:
    - "8020:3000"
    - "8022:22"
  links:
    - "postgres"
  volumes_from:
    - 'gogs_data'

postgres:
  image: "postgres:latest"
  container_name: "git-db"
  restart: 'always'
  expose:
    - "5432"
  volumes_from:
    - 'gogs_data'
  environment:
    - "POSTGRES_DB=gogs"
    - "POSTGRES_USER=gogs"
    - "POSTGRES_PASSWORD=gogs"
