# Gogs

gogs_data:
  image: 'busybox'
  tty: true
  container_name: 'gogs-data'
  volumes:
    - '/var/gogs/data:/data'
    - '/var/gogs/postgres:/var/lib/postgres'

gogs:
  image: "gogs/gogs"
  container_name: "gogs-srv"
  restart: 'always'
  ports:
    - "8020:3000"
    - "8022:22"
  links:
    - "postgres"
  volumes_from:
    - 'gogs_data'

postgres:
  image: "postgres"
  container_name: "gogs-db"
  restart: 'always'
  expose:
    - "5432"
  volumes_from:
    - 'gogs_data'
  environment:
    - "POSTGRES_DB=gogs"
    - "POSTGRES_USER=gogs"
    - "POSTGRES_PASSWORD=gogs"
