# Storage Server

MAINTAINER jcmdln

FROM alpine:latest
RUN apk update -y && apk upgrade -y && apk add --update samba krb5 krb5-libs openldap openldap-clients openldap-back-hdb openldap-back-bdb ldapvi
