# NextCloud

version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: postgres
    restart: always
    ports:
      - 8026:5432
    volumes:
      - db:/var/lib/postgres
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud

  app:
    image: nextcloud
    ports:
      - 8025:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
