# Network Management Server

MAINTAINER jcmdln

FROM alpine:latest
RUN apk update -y && apk upgrade -y && apk add --update caddy

# I could inject `heartbeat` into this via git, though I will look around for alternative methods
